name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn build
        run: yarn build
      - name: yarn test
        run: yarn test
